name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
version-template: '$MAJOR.$MINOR.$PATCH'

categories:
  - title: '## Features'
    labels:
      - 'feat'
      - 'feature'
  - title: '## Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: '## Documentation'
    labels:
      - 'docs'
      - 'documentation'
  - title: '## Chores'
    labels:
      - 'chore'
      - 'maintenance'

change-template: '- $TITLE ([#$NUMBER]($URL)) ([`$SHORT_SHA`]($COMMIT_URL)) by @$AUTHOR'

autolabeler:
  - label: 'feat'
    title: '^feat'
  - label: 'fix'
    title: '^fix'
  - label: 'docs'
    title: '^docs'
  - label: 'chore'
    title: '^chore'

exclude-labels:
  - 'duplicate'
  - 'invalid'
  - 'question'
  - 'wontfix'

template: |
  # :sparkles: $MONTH Release

  **Version**: v$NEXT_PATCH_VERSION

  Thank you to all contributors!

  ## Changelog

  $CHANGES

  Check below for Downloads!
