name: Release Builder

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  # Windows Build
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Run Windows Build Script
        run: scripts\build_windows.bat
        shell: cmd

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: dist/*.exe  # Windows executable in dist/

  # Linux Build
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y patchelf fuse libfuse2 wget
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          pip install build

      - name: Make Build Scripts Executable
        run: |
          chmod +x scripts/build_linux.sh
          chmod +x scripts/build_appimage.sh

      - name: Run Linux Build Script
        run: scripts/build_linux.sh
        shell: bash

      - name: Run AppImage Build Script
        run: scripts/build_appimage.sh
        shell: bash

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: dist/*  # Linux and AppImage in dist/

  # macOS Build
  macos-build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          brew install pyinstaller
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Make Build Script Executable
        run: chmod +x scripts/build_mac.sh

      - name: Run macOS Build Script
        run: scripts/build_mac.sh
        shell: bash

      - name: Upload macOS Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos-build
          path: dist/*  # macOS DMG in dist/

