name: Release Drafter

on:
  release:
    types: [created]

jobs:
  update-release-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Get the current month
        id: get_month
        run: echo "::set-output name=month::$(date +'%B')"

      - name: Update Release Draft
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const month = "${{ steps.get_month.outputs.month }}";
            const release = await github.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: context.payload.release.tag_name,
            });
            await github.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.data.id,
              name: `✨ ${month} Release`,
            });
