name: Release Builder

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  # Windows Build
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Run Windows Build Script
        run: scripts\build_windows.bat
        shell: cmd

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: dist\*.exe

  # Linux Build
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y patchelf fuse libfuse2 wget
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          pip install build

      - name: Make Build Scripts Executable
        run: |
          chmod +x scripts/build_linux.sh
          chmod +x scripts/build_appimage.sh

      - name: Run Linux Build Script
        run: scripts/build_linux.sh
        shell: bash

      - name: Run AppImage Build Script
        run: scripts/build_appimage.sh
        shell: bash

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: dist/*

  # macOS Build
  macos-build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          brew install pyinstaller
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Make Build Script Executable
        run: chmod +x scripts/build_mac.sh

      - name: Run macOS Build Script
        run: scripts/build_mac.sh
        shell: bash

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos-build
          path: dist/*

  # Collect Artifacts
  collect-artifacts:
    name: Collect Artifacts
    needs: [windows-build, linux-build, macos-build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Windows Artifacts
        uses: actions/download-artifact@v3
        with:
          name: windows-build
          path: dist/windows/

      - name: Download Linux Artifacts
        uses: actions/download-artifact@v3
        with:
          name: linux-build
          path: dist/linux/

      - name: Download macOS Artifacts
        uses: actions/download-artifact@v3
        with:
          name: macos-build
          path: dist/macos/

      - name: Upload Combined Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: OnTheSpot-Builds
          path: dist/

      - name: Create Release
        if: github.event_name == 'release'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.release.tag_name }}
          release_name: ${{ github.event.release.name }}
          draft: false
          prerelease: false

      - name: Upload Windows Executable to Release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/windows/onthespot_win*.exe
          asset_name: onthespot_windows.exe
          asset_content_type: application/octet-stream

      - name: Upload Linux Executable to Release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/linux/onthespot_linux*
          asset_name: onthespot_linux
          asset_content_type: application/octet-stream

      - name: Upload Linux AppImage to Release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/linux/OnTheSpot-x86_64.AppImage
          asset_name: OnTheSpot.AppImage
          asset_content_type: application/octet-stream

      - name: Upload macOS DMG to Release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/macos/OnTheSpot.dmg
          asset_name: OnTheSpot.dmg
          asset_content_type: application/x-apple-diskimage
